# Generated by Django 4.2.8 on 2024-01-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0034_navigation_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='slogan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
