# Generated by Django 4.2.8 on 2024-01-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0035_globalsettings_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
